### ISSUE TITLE
Ubuntu 16.04 wxwidgets 3.0.2 problem

### ISSUE THREAD

**Issue by richud** [tgvaughan/PirateScope#4]
Hi,
Cheers for software !  but this seems to no longer work in Ubuntu 16.04 ;

```
$ ./PirateScope 
Traceback (most recent call last):
  File "./PirateScope", line 762, in <module>
    frame = MainWindow(None, 'PirateScope')
  File "./PirateScope", line 274, in __init__
    self.plot = plot.PlotCanvas(self.plotpanel)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/lib/plot.py", line 598, in __init__
    self.HandCursor = wx.Cursor(Hand.GetImage())
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_gdi.py", line 1510, in __init__
    _gdi_.Cursor_swiginit(self,_gdi_.new_Cursor(*args, **kwargs))
TypeError: Required argument 'type' (pos 2) not found

```

**Comment by tgvaughan** [comment]
Hi @richud, thanks for pointing this out.  I don't have a lot of time to spend working on this any more, so it may take me a while to get around to fixing this.  Feel free to fork and have a crack on your own though!

**Comment by jabbink** [comment]
Confirmed problem in wxpython 3.0.2.0

http://trac.wxwidgets.org/ticket/16924

**Comment by tgvaughan** [comment]
Thanks @jabbink for identifying the upstream wxpython issue.  As that issue is now closed, I'm also closing this one.
