### ISSUE TITLE
 No module named serial

### ISSUE THREAD

**Issue by gerisse** [tgvaughan/PirateScope#5]
i use it with Archlinux. Thanks
There is a aur repository : https://aur.archlinux.org/packages/piratescope-git/
But , after installation , not run ; the message is :
File "/usr/bin/piratescope", line 26, in <module>
    import serial, time, sys, os
ImportError: No module named serial
 Perhaps beacause my os uses python 3 ?
Or, if not, what s the problem ?
Thanks

**Comment by tgvaughan** [comment]
Hi @gerisse. Had no idea someone had packaged this up.  Interesting!  Yes, this is definitely a Python 2 package (see README.md for other dependencies and installation instructions) so you'll need to install that before you can use it.  Good luck!

**Comment by gerisse** [comment]
Hi Tim. ok, but python 2 is installed in my PC. But i don't know how to force tu use version 2. With a script python, i see but not with a binary.
Thanks

**Comment by tgvaughan** [comment]
Hi @gerisse, you'll have to ask the maintainer of the Arch package.  This is listed as "dobo" on https://aur.archlinux.org/packages/piratescope-git/,  but I'm not sure what the idiomatic way to get in touch with them is.  (Perhaps via the "submit request" link on the arch package page?  I don't know, never used Arch...)

The other alternative is to just download it from this repository and run it directly.  (Making sure the dependencies are met, of course.)

**Comment by gerisse** [comment]
thanks for your response
I solved it : i set up serial with pip in version 2 (and not 3, in my case, by default), so, in cli :
sudo pip2 install pyserial
